// 浏览器演示模式用的假数据（architecture.md §7.3；只读，不参与任何真实调用）
import type {
  AppConfig,
  ArchiveAssessment,
  MergeCheckResult,
  ProjectResolution,
  RemoteBranches,
  RemovalAssessment,
  WorkspaceGroup,
} from "../types";

export const demoConfig: AppConfig = {
  schemaVersion: 1,
  workspaceRoot: "/Users/demo/Work/workspace",
  sharedDirectories: [{ sourcePath: "/Users/demo/Work/fd-common", targetDirectory: "fd-common" }],
  projects: [
    { id: "api3", repositoryPath: "/Users/demo/Work/php-project/api3", projectType: "php", vendorAvailable: true },
    { id: "web-portal", repositoryPath: "/Users/demo/Work/php-project/web-portal", projectType: "php", vendorAvailable: false },
    { id: "gateway", repositoryPath: "/Users/demo/Work/go-project/gateway", projectType: "go", vendorAvailable: false },
  ],
  recentIterations: ["7.3.0", "7.2.1", "7.2.0"],
};

export const demoWorkspaceGroups: WorkspaceGroup[] = [
  {
    iteration: "7.3.0",
    iterationPath: "/Users/demo/Work/workspace/7.3.0",
    manifestHealth: "valid",
    manifestMessage: null,
    openable: true,
    note: "等 QA 回归后归档",
    hiddenAt: null,
    sharedDirectories: [
      {
        ruleId: "fd-common",
        sourcePath: "/Users/demo/Work/fd-common",
        targetDirectory: "fd-common",
        targetPath: "/Users/demo/Work/workspace/7.3.0/fd-common",
        status: "copied",
        message: null,
      },
    ],
    projects: [
      {
        projectId: "api3",
        branchDisplay: "feature/7.3.0-api",
        baseCommit: "4f2ab1c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3",
        baseRef: "origin/master",
        sourceRepository: "/Users/demo/Work/php-project/api3",
        worktreePath: "/Users/demo/Work/workspace/7.3.0/api3",
        vendorStatus: "copied",
        createdAt: "2026-07-30T10:01:00Z",
        validity: "valid",
        openable: true,
        removable: true,
        renamedFrom: null,
        dirty: false,
        hasChanges: false,
        lifecycle: "active",
      },
      {
        projectId: "web-portal",
        branchDisplay: "feature/7.3.0-portal",
        baseCommit: "9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b",
        baseRef: "origin/develop",
        sourceRepository: "/Users/demo/Work/php-project/web-portal",
        worktreePath: "/Users/demo/Work/workspace/7.3.0/web-portal",
        vendorStatus: "notPhp",
        createdAt: "2026-07-30T10:02:00Z",
        validity: "valid",
        openable: true,
        removable: true,
        renamedFrom: "feature/7.3.0-web",
        dirty: true,
        hasChanges: true,
        lifecycle: "active",
      },
      {
        projectId: "gateway",
        branchDisplay: "detached @ 1a2b3c4",
        baseCommit: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
        baseRef: "origin/master",
        sourceRepository: "/Users/demo/Work/go-project/gateway",
        worktreePath: "/Users/demo/Work/workspace/7.3.0/gateway",
        vendorStatus: null,
        createdAt: "2026-07-30T10:03:00Z",
        validity: "unknown",
        openable: true,
        removable: true,
        renamedFrom: null,
        dirty: null,
        hasChanges: null,
        lifecycle: "active",
      },
      {
        projectId: "legacy-tools",
        branchDisplay: "feature/7.3.0-legacy",
        baseCommit: null,
        baseRef: "origin/master",
        sourceRepository: "/Users/demo/Work/php-project/legacy-tools",
        worktreePath: "/Users/demo/Work/workspace/7.3.0/legacy-tools",
        vendorStatus: null,
        createdAt: "2026-07-30T10:04:00Z",
        validity: "missingDirectory",
        openable: false,
        removable: false,
        renamedFrom: null,
        dirty: null,
        hasChanges: null,
        lifecycle: "createFailed",
      },
    ],
  },
  {
    iteration: "7.2.1",
    iterationPath: "/Users/demo/Work/workspace/7.2.1",
    manifestHealth: "valid",
    manifestMessage: null,
    openable: true,
    note: null,
    hiddenAt: null,
    sharedDirectories: [],
    projects: [
      {
        projectId: "api3",
        branchDisplay: "release/7.2.1",
        baseCommit: "2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1e",
        baseRef: "origin/release",
        sourceRepository: "/Users/demo/Work/php-project/api3",
        worktreePath: "/Users/demo/Work/workspace/7.2.1/api3",
        vendorStatus: "lockMismatch",
        createdAt: "2026-07-12T09:20:00Z",
        validity: "removed",
        openable: false,
        removable: false,
        renamedFrom: null,
        dirty: null,
        hasChanges: null,
        lifecycle: "removed",
      },
    ],
  },
  {
    iteration: "6.9.0",
    iterationPath: "/Users/demo/Work/workspace/6.9.0",
    manifestHealth: "damaged",
    manifestMessage: "清单解析失败：expected value at line 1 column 1",
    openable: true,
    note: null,
    hiddenAt: null,
    sharedDirectories: [],
    projects: [],
  },
  {
    iteration: "7.2.0",
    iterationPath: "/Users/demo/Work/workspace/7.2.0",
    manifestHealth: "valid",
    manifestMessage: null,
    openable: true,
    note: "旧迭代",
    hiddenAt: "2026-07-20T08:00:00Z",
    sharedDirectories: [],
    projects: [
      {
        projectId: "api3",
        branchDisplay: "feature/7.2.0-api",
        baseCommit: null,
        baseRef: "origin/master",
        sourceRepository: "/Users/demo/Work/php-project/api3",
        worktreePath: "/Users/demo/Work/workspace/7.2.0/api3",
        vendorStatus: "copied",
        createdAt: "2026-07-02T10:00:00Z",
        validity: "valid",
        openable: true,
        removable: true,
        renamedFrom: null,
        dirty: false,
        hasChanges: false,
        lifecycle: "active",
      },
    ],
  },
];

export const demoProjectResolutions: ProjectResolution[] = [
  {
    inputPath: "/Users/demo/Work/php-project/api3",
    repositoryPath: "/Users/demo/Work/php-project/api3",
    suggestedId: "api3",
    projectType: "php",
    vendorAvailable: true,
    error: null,
  },
  {
    inputPath: "/Users/demo/Work/go-project/gateway",
    repositoryPath: "/Users/demo/Work/go-project/gateway",
    suggestedId: "gateway",
    projectType: "go",
    vendorAvailable: false,
    error: null,
  },
];

export const demoRemoteBranches: RemoteBranches = {
  projectId: "api3",
  remotes: ["origin", "upstream"],
  branches: ["origin/develop", "origin/master", "origin/release", "upstream/develop"],
  source: "local",
  warning: null,
};

export const demoMergeCheckResult: MergeCheckResult = {
  iteration: "7.3.0",
  checkedAt: "2026-07-31T09:30:00Z",
  records: [
    {
      projectId: "api3",
      branchDisplay: "feature/7.3.0-api",
      worktreePath: "/Users/demo/Work/workspace/7.3.0/api3",
      lifecycle: "active",
      develop: { status: "merged", unmergedCommits: [], errorMessage: null, stale: false, dirty: false },
      master: { status: "unmerged", unmergedCommits: ["9f8e7d6 修正结算精度"], errorMessage: null, stale: false, dirty: false },
      hasChanges: false,
      dirty: false,
    },
    {
      projectId: "web-portal",
      branchDisplay: "feature/7.3.0-portal",
      worktreePath: "/Users/demo/Work/workspace/7.3.0/web-portal",
      lifecycle: "active",
      develop: { status: "contained", unmergedCommits: [], errorMessage: null, stale: true, dirty: false },
      master: { status: "targetMissing", unmergedCommits: [], errorMessage: null, stale: false, dirty: false },
      hasChanges: true,
      dirty: true,
    },
  ],
};

export const demoRemovalAssessment: RemovalAssessment = {
  iteration: "7.3.0",
  projectId: "api3",
  worktreePath: "/Users/demo/Work/workspace/7.3.0/api3",
  confirmationText: "7.3.0/api3",
  allowed: false,
  vendorOnlyCleanupAvailable: false,
  risks: [
    { code: "untrackedFiles", severity: "blocking", message: "存在未跟踪文件", paths: ["notes/todo.md"] },
    { code: "trackedChanges", severity: "blocking", message: "存在已跟踪文件的未提交修改", paths: ["src/order/calc.php"] },
  ],
};

export const demoDiscoveredRemovalAssessment: RemovalAssessment = {
  iteration: "7.3.0",
  projectId: "",
  worktreePath: "/Users/demo/Work/workspace/7.3.0/ghost-lib",
  confirmationText: "7.3.0/ghost-lib",
  allowed: true,
  vendorOnlyCleanupAvailable: false,
  risks: [],
};

export const demoArchiveAssessment: ArchiveAssessment = {
  iteration: "7.3.0",
  confirmationText: "7.3.0",
  checkedAt: "2026-07-31T09:40:00Z",
  clean: false,
  records: [
    {
      projectId: "api3",
      branchDisplay: "feature/7.3.0-api",
      worktreePath: "/Users/demo/Work/workspace/7.3.0/api3",
      develop: { status: "merged", unmergedCommits: [], errorMessage: null, stale: false, dirty: false },
      master: { status: "unmerged", unmergedCommits: ["9f8e7d6 修正结算精度"], errorMessage: null, stale: false, dirty: false },
      dirty: false,
      clean: false,
      blockers: ["master：未合并 1 个提交"],
    },
    {
      projectId: "web-portal",
      branchDisplay: "feature/7.3.0-portal",
      worktreePath: "/Users/demo/Work/workspace/7.3.0/web-portal",
      develop: { status: "merged", unmergedCommits: [], errorMessage: null, stale: false, dirty: false },
      master: { status: "targetMissing", unmergedCommits: [], errorMessage: null, stale: false, dirty: false },
      dirty: false,
      clean: true,
      blockers: [],
    },
  ],
};

